# Generated by Django 2.2.2 on 2020-02-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=200)),
                ('type_product', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=200)),
                ('conversion_rate', models.IntegerField(default=0)),
                ('commission_rate', models.IntegerField(default=0)),
            ],
        ),
    ]
