# Generated by Django 2.2.2 on 2020-02-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_product', models.IntegerField(choices=[(1, 'Tử kỳ'), (2, 'Sức khoẻ'), (3, 'Du lịch'), (4, 'Ô tô'), (5, 'Đầu tư')], default=0)),
                ('company', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('commission_rate', models.FloatField(default=0.0)),
                ('is_nhan_tho', models.BooleanField(default=True)),
            ],
        ),
    ]
