# Generated by Django 2.2.2 on 2020-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertproduct',
            name='name_product',
        ),
        migrations.AddField(
            model_name='convertproduct',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='convertproduct',
            name='commission_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='convertproduct',
            name='company',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='convertproduct',
            name='conversion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='convertproduct',
            name='type_product',
            field=models.IntegerField(choices=[(1, 'Tử kỳ'), (2, 'Sức khoẻ'), (3, 'Du lịch'), (4, 'Ô tô'), (5, 'Đầu tư')], default=0),
        ),
    ]
