# Generated by Django 2.2.2 on 2020-02-22 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert_product', '0002_auto_20200221_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertproduct',
            name='product_id',
        ),
    ]
