# Generated by Django 2.2.2 on 2020-02-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_product', '0003_remove_convertproduct_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertproduct',
            name='is_nhan_tho',
            field=models.BooleanField(default=True),
        ),
    ]
