# Generated by Django 2.2.2 on 2020-03-29 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_commission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welfarecommissions',
            name='end_payment',
        ),
        migrations.RemoveField(
            model_name='welfarecommissions',
            name='start_payment',
        ),
        migrations.RemoveField(
            model_name='welfarecommissions',
            name='status_car',
        ),
        migrations.RemoveField(
            model_name='welfarecommissions',
            name='status_home',
        ),
        migrations.RemoveField(
            model_name='welfarecommissions',
            name='status_tourist',
        ),
        migrations.AddField(
            model_name='welfarecommissions',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='welfarecommissions',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='welfarecommissions',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='welfarecommissions',
            name='type_an_sinh',
            field=models.IntegerField(choices=[(0, 'Du lịch'), (1, 'Xe'), (2, 'Nhà')], default=-1),
        ),
    ]
