# Generated by Django 2.2.2 on 2020-02-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid_mua', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=200)),
                ('number_YCBH', models.CharField(max_length=200)),
                ('number_policy', models.CharField(max_length=200)),
                ('company', models.IntegerField(choices=[(1, 'Bảo Việt'), (2, 'Cathay')])),
                ('name_product', models.CharField(max_length=200)),
                ('sumit_date', models.DateField()),
                ('release_date', models.DateField()),
                ('ack_date', models.DateField()),
                ('ack_status', models.IntegerField(choices=[(0, 'Chưa ACK'), (1, 'Đã ACK')], default=0)),
                ('status_policy', models.IntegerField(default=0)),
                ('premium', models.IntegerField(default=0)),
                ('bv_premium', models.IntegerField(default=0)),
                ('status_payment', models.IntegerField(choices=[(0, 'Chưa thanh toán'), (1, 'Đã Thanh Toán'), (2, 'Thanh Toán Thất Bại')], default=0)),
                ('certificate', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('is_rewarded', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonLifeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('number_YCBH', models.CharField(max_length=200)),
                ('number_policy', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('name_product', models.CharField(max_length=200)),
                ('sumit_date', models.DateField()),
                ('release_date', models.DateField()),
                ('status_policy', models.IntegerField(default=0)),
                ('premium', models.IntegerField(default=0)),
                ('bv_premium', models.IntegerField(default=0)),
                ('status_payment', models.IntegerField(default=0)),
                ('certificate', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
