# Generated by Django 2.2.2 on 2020-02-21 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonLifeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('number_YCBH', models.CharField(max_length=200)),
                ('number_policy', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('name_product', models.CharField(max_length=200)),
                ('sumit_date', models.DateField()),
                ('release_date', models.DateField()),
                ('status_policy', models.IntegerField(default=0)),
                ('premium', models.IntegerField(default=0)),
                ('bv_premium', models.IntegerField(default=0)),
                ('status_payment', models.IntegerField(default=0)),
                ('certificate', models.FileField(upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LifeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('number_YCBH', models.CharField(max_length=200)),
                ('number_policy', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('name_product', models.CharField(max_length=200)),
                ('sumit_date', models.DateField()),
                ('release_date', models.DateField()),
                ('ack_date', models.DateField()),
                ('status_policy', models.IntegerField(default=0)),
                ('premium', models.IntegerField(default=0)),
                ('bv_premium', models.IntegerField(default=0)),
                ('status_payment', models.IntegerField(default=0)),
                ('certificate', models.FileField(upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
