# Generated by Django 2.2.2 on 2020-02-29 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convert_product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy_insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonlifeproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lifeproduct',
            name='type_product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='convert_product.ConvertProduct'),
        ),
        migrations.AddField(
            model_name='lifeproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
