# Generated by Django 2.2.2 on 2020-02-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeproduct',
            name='certificate',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='lifeproduct',
            name='company',
            field=models.IntegerField(choices=[(1, 'Bảo Việt'), (2, 'Cathay')]),
        ),
        migrations.AlterField(
            model_name='lifeproduct',
            name='status_payment',
            field=models.IntegerField(choices=[(0, 'Chưa thanh toán'), (1, 'Đã Thanh Toán'), (2, 'Thanh Toán Thất Bại')], default=0),
        ),
    ]
