# Generated by Django 2.2.2 on 2020-02-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_insurance', '0002_auto_20200221_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeproduct',
            name='certificate',
            field=models.FileField(default=None, null=True, upload_to='uploads/'),
        ),
    ]
