# Generated by Django 2.2.2 on 2020-02-22 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convert_product', '0003_remove_convertproduct_product_id'),
        ('policy_insurance', '0003_auto_20200221_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeproduct',
            name='type_product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='convert_product.ConvertProduct'),
        ),
    ]
