# Generated by Django 2.2.2 on 2020-02-22 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('policy_insurance', '0004_lifeproduct_type_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeproduct',
            name='ack_status',
            field=models.IntegerField(choices=[(1, 'Chưa ACK'), (2, 'Đã ACK')], default=0),
        ),
        migrations.AddField(
            model_name='lifeproduct',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 22, 5, 30, 54, 159026, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifeproduct',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
