# Generated by Django 2.2.2 on 2020-02-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_insurance', '0005_auto_20200222_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeproduct',
            name='is_rewarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lifeproduct',
            name='ack_status',
            field=models.IntegerField(choices=[(0, 'Chưa ACK'), (1, 'Đã ACK')], default=0),
        ),
    ]
