# Generated by Django 2.2.2 on 2020-02-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_number', models.IntegerField(default=0)),
                ('branch', models.CharField(max_length=200)),
                ('date_create', models.DateField()),
            ],
        ),
    ]
