# Generated by Django 2.2.2 on 2020-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_bankaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='date_create',
            field=models.DateField(auto_now=True),
        ),
    ]
