# Generated by Django 2.2.2 on 2020-02-29 07:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userid', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=200)),
                ('sex', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200, null=True)),
                ('datecreate', models.DateField(auto_now=True, null=True)),
                ('dob', models.DateField(null=True)),
                ('level', models.IntegerField(default=0)),
                ('personal_points', models.IntegerField(default=0)),
                ('cmnd_number', models.CharField(default=None, max_length=200, null=True)),
                ('cmnd_date', models.DateField(null=True)),
                ('cmnd_address', models.CharField(max_length=200, null=True)),
                ('city', models.IntegerField(default=0, null=True)),
                ('tax_number', models.CharField(default=None, max_length=200, null=True)),
                ('tax_address', models.CharField(max_length=200, null=True)),
                ('position', models.IntegerField(default=0)),
                ('status_id', models.IntegerField(default=0)),
                ('retail_commission', models.IntegerField(default=0)),
                ('recruitment_commission', models.IntegerField(default=0)),
                ('mutual_commissions', models.IntegerField(default=0)),
                ('group_commissions', models.IntegerField(default=0)),
                ('group_commissions2', models.IntegerField(default=0)),
                ('career_commission', models.IntegerField(default=0)),
                ('career_commission2', models.IntegerField(default=0)),
                ('welfare_commission', models.IntegerField(default=0)),
                ('policy_commission', models.IntegerField(default=0)),
                ('bv_green', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('id_1_sponser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_1_sponser_us', to=settings.AUTH_USER_MODEL)),
                ('id_2_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_2_child_us', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_u', to=settings.AUTH_USER_MODEL)),
                ('sponser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponser_u', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ViTien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bv_point', models.IntegerField(default=0)),
                ('bv_status', models.IntegerField(choices=[(0, 'Đỏ'), (1, 'Xanh')], default=0)),
                ('description', models.CharField(max_length=200, null=True)),
                ('source', models.IntegerField(choices=[(0, 'Không rõ'), (1, 'Từ hợp đồng bảo hiểm nhân thọ'), (2, 'Từ hợp đồng bảo hiểm phi nhân thọ'), (3, 'Từ thưởng hoa hồng đội nhóm'), (4, 'Từ hoa hồng bán lẻ PNT'), (5, 'Từ hoa hồng bán lẻ Nhan Tho'), (6, 'Từ  hoa hồng maketing'), (7, 'Từ hoa hồng tuyển dụng'), (8, 'Từ hoa hồng cấp bậc')], default=0)),
                ('time_active', models.IntegerField(default=10)),
                ('da_chuyen_qua_vi_xanh', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.CreateModel(
            name='LogTuyenDung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bv_tuyendung', models.IntegerField(default=0)),
                ('id_cua_nguoi_duoc_tuyen', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('num_date', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_history',
            },
        ),
        migrations.CreateModel(
            name='LogChuyenTien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bv_point', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vitien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ViTien')),
            ],
        ),
    ]
