# Generated by Django 2.2.2 on 2020-02-21 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_wallet', models.IntegerField(default=0)),
                ('green_wallet', models.IntegerField(default=0)),
                ('bank_account', models.TextField(blank=True)),
                ('amount_withdraw', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_number', models.IntegerField(default=0)),
                ('branch', models.CharField(max_length=200)),
                ('date_create', models.DateField(auto_now=True)),
                ('date_payment', models.DateField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
